In [3]:
import numpy as np
a=np.random.rand(5)
a

array([0.58721248, 0.64109239, 0.10882121, 0.84147334, 0.80704862])

In [4]:
a.shape

(5,)

In [5]:
a.T

array([0.58721248, 0.64109239, 0.10882121, 0.84147334, 0.80704862])

In [6]:
print(np.dot(a,a.T))

2.1270648758967474


In [7]:
a=np.random.randn(5,1)
a

array([[ 0.94330313],
       [ 1.41776731],
       [ 0.00874926],
       [-1.62199324],
       [-0.65281237]])

In [8]:
# taking tanspose of a we get a row vector of a
# the diiference is in this way we get the two bracket andget a (1,5) matrix and the previous way we get the rank one array
a.T

array([[ 0.94330313,  1.41776731,  0.00874926, -1.62199324, -0.65281237]])

In [9]:
np.dot(a,a.T)

array([[ 8.89820795e-01,  1.33738434e+00,  8.25320795e-03,
        -1.53003130e+00, -6.15799949e-01],
       [ 1.33738434e+00,  2.01006414e+00,  1.24044202e-02,
        -2.29960899e+00, -9.25536032e-01],
       [ 8.25320795e-03,  1.24044202e-02,  7.65496174e-05,
        -1.41912468e-02, -5.71162763e-03],
       [-1.53003130e+00, -2.29960899e+00, -1.41912468e-02,
         2.63086208e+00,  1.05885725e+00],
       [-6.15799949e-01, -9.25536032e-01, -5.71162763e-03,
         1.05885725e+00,  4.26163987e-01]])

In [17]:
b=np.random.randn(1228,150)
d=np.random.randn(150,45)
c=np.dot(b,d)
c

array([[-32.01689604,  17.37096487,  -9.05734951, ...,   8.0275222 ,
         29.91654634,   1.31774604],
       [ 15.81663725,  15.90824526,  -7.39201127, ...,   4.36045029,
         -5.45416523,   5.63988181],
       [ -2.37869604,  -4.4037153 , -14.76737243, ...,  -5.19171581,
         -7.55600324,  -7.28189968],
       ...,
       [  5.27189768, -27.68869533,   2.36227508, ..., -13.60485352,
        -13.81958978,  11.4698133 ],
       [-14.58653541,  -0.51421657,  -0.87719851, ..., -16.51977055,
         14.61464723,  -7.12227071],
       [-10.53005245,  -4.77297173,  -3.2696385 , ...,  -1.68727561,
         -6.85506387,  -4.42624181]])

In [19]:
c.shape

(1228, 45)

In [27]:
b=np.random.randn(2,3)
d=np.random.randn(2,1)
c=b+d
c
c.shape

(2, 3)

In [25]:
a=np.random.randn(3,3)

b = np.random.randn(3, 1)

c = a*b
c
c.shape

(3, 3)